import React, { useState } from 'react';
import Head from 'next/head';
// import { Inter } from '@next/font/google';
import { useRouter } from 'next/router';
import { useDispatch, useSelector } from 'react-redux';

import { apicall, getUserDetails } from 'utils';
import { LOGIN_URL, TOKEN, USER } from 'routes';

// const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const router = useRouter();
  const dispatch = useDispatch();

  const [requestToken, setRequestToken] = useState('');
  const userState = useSelector(state => state[USER]);

  const { data: { kycName = '' } = {} } = userState || {};

  const handleLogin = async () => {
    const { loginUrl } = await apicall({ route: LOGIN_URL });
    if (loginUrl) router.push(loginUrl);
  };

  const saveRequestToken = async e => {
    e?.preventDefault();
    localStorage.setItem('requestToken', requestToken);
  };

  const getAccessToken = async () => {
    const reqToken = localStorage.getItem('requestToken');
    const response = await apicall({
      route: TOKEN,
      method: 'POST',
      body: { requestToken: reqToken },
    });
    const { data } = response || {};
    if (data) {
      localStorage.setItem('token', data);
      const userDetails = await getUserDetails();
      dispatch({ type: USER, payload: userDetails });
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {kycName ? (
          <p>
            <strong>welcome</strong> {kycName}
          </p>
        ) : (
          <>
            <button onClick={handleLogin}>Go to Paytm Money</button>
            <br />
            <br />
            <form onSubmit={saveRequestToken}>
              <input onChange={e => setRequestToken(e.target.value)} />
              <button type="submit">submit</button>
            </form>
            <br />
            <button onClick={getAccessToken}>Get Access Token</button>
          </>
        )}
      </main>
    </>
  );
}
